### ISSUE TITLE
Event Editor

### ISSUE THREAD

**Issue by soulshaker3** [borisblizzard/arcreator#26]
## Tasks to the event editor
 - [ ] #25 Event commands
 - [ ] event exporter to XML            
 - [ ] event XML parser                  
 - [ ] editor panel via virtual HTML list     [PARTIAL]
